using System.Collections.Generic;
using System.Linq;

namespace VL.Yoga.Generator.Sources
{
    public static class ConfigSource
    {
        public static string CLASS_NAME = "Config";
        public static string INTERFACE_NAME = "IFlexConfig";

        public static Dictionary<string, Dictionary<string, string>> NODES = new()
        {
            ["UseWebDefaults"] = new() { ["bool"] = "enabled" },
            ["PointScaleFactor"] = new() { ["float"] = "pixelsInPoint" },
            ["Errata"] = new() { ["YGErrata"] = "errata" },
            ["ExperimentalFeatureEnabled"] = new() { ["YGExperimentalFeature"] = "feature", ["bool"] = "enabled" },
        };

        public static string YogaConfigSource() => @$"
        // <auto-generated/>
        #nullable enable

        using YogaSharp;

        namespace Flex
        {{
            public partial class {CLASS_NAME} 
            {{
                {string.Join("\r\n", NODES.Select((style) => YogaConfigNodeImplementation(style.Key, style.Value)))}
            }}
        }}
        ";

        public static string YogaConfigNodeImplementation(string name, Dictionary<string, string> attributes)
        {
            var hasAttributes = attributes.Count > 0;

            return @$"   
        public record struct {CLASS_NAME}{name}({INTERFACE_NAME}? Config{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => $"{value.Key} {value.Value.ToPascalCase()}"))}) : {INTERFACE_NAME}
        {{
            public void ApplyConfig(FlexConfig node, IFlexConfig config)
            {{
                unsafe 
                {{
                    Interop.YGConfigSet{name}(node.GetHandle(){(hasAttributes ? ", " : "")}{(hasAttributes ? string.Join(", ", attributes.Select((value) => value.Value.ToPascalCase())) : "")});
                    Config?.ApplyConfig(node, config);
                }}
            }}
        }}

        public static {CLASS_NAME}{name} Set{name}({INTERFACE_NAME}? style{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => $"{value.Key} {value.Value}"))}) => new {CLASS_NAME}{name}(style{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => value.Value))});
        ";
        }
    }
}
