using System.Collections.Generic;
using System.Linq;

namespace VL.Yoga.Generator.Sources
{
    public static class ConfigSource
    {
        public static string CLASS_NAME = "Config";
        public static string INTERFACE_NAME = "IFlexConfig";

        public static Dictionary<string, Dictionary<string, string>> NODES = new()
        {
            ["UseWebDefaults"] = new() { ["bool"] = "enabled" },
            ["PointScaleFactor"] = new() { ["float"] = "pixelsInPoint" },
            ["Errata"] = new() { ["YGErrata"] = "errata" },
        };

        public static string YogaConfigSource() => @$"
        // <auto-generated/>
        #nullable enable

        using YogaSharp;

        namespace Flex
        {{
            public static partial class {CLASS_NAME} 
            {{
                {string.Join("\r\n", NODES.Select((style) => FlexConfigSetter(style.Key, style.Value)))}
            }}
        }}

        namespace Flex.Internal
        {{
            {string.Join("\r\n", NODES.Select((style) => FlexConfigStruct(style.Key, style.Value)))}
        }}
        ";

        public static string FlexConfigSetter(string name, Dictionary<string, string> attributes)
        {
            var hasAttributes = attributes.Count > 0;
            return $@"
            public static Internal.{CLASS_NAME}{name} Set{name}({INTERFACE_NAME}? config{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => $"{value.Key} {value.Value}"))}) => new(config{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => value.Value))});
            ";
        }

        public static string FlexConfigStruct(string name, Dictionary<string, string> attributes)
        {
            var hasAttributes = attributes.Count > 0;
            return $@"
                public unsafe record struct {CLASS_NAME}{name}({INTERFACE_NAME}? Config{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => $"{value.Key} {value.Value.ToPascalCase()}"))}) : {INTERFACE_NAME}
                {{
                    public unsafe void ApplyConfig(YGConfig* handle)
                    {{
                        handle->Set{name}({(hasAttributes ? string.Join(", ", attributes.Select((value) => value.Value.ToPascalCase())) : "")});
                        Config?.ApplyConfig(handle);
                    }}
                }}
            ";
        }
    }
}
