using System.Collections.Generic;
using System.Linq;

namespace VL.Yoga.Generator.Sources
{
    public static class StyleSource
    {
        public static Dictionary<string, Dictionary<string, string>> STYLES = new()
        {
            ["Direction"] = new() { ["YGDirection"] = "direction" },
            ["FlexDirection"] = new() { ["YGFlexDirection"] = "flexDirection" },
            ["AlignContent"] = new() { ["YGAlign"] = "alignContent" },
            ["AlignItems"] = new() { ["YGAlign"] = "alignItems" },
            ["AlignSelf"] = new() { ["YGAlign"] = "alignSelf" },
            ["PositionType"] = new() { ["YGPositionType"] = "positionType" },
            ["FlexWrap"] = new() { ["YGWrap"] = "flexWrap" },
            ["Overflow"] = new() { ["YGOverflow"] = "overflow" },
            ["Display"] = new() { ["YGDisplay"] = "display" },
            ["Flex"] = new() { ["float"] = "flex" },
            ["FlexGrow"] = new() { ["float"] = "flexGrow" },
            ["FlexShrink"] = new() { ["float"] = "flexShrink" },
            ["FlexBasis"] = new() { ["float"] = "flexBasis" },
            ["FlexBasisPercent"] = new() { ["float"] = "flexBasisPercent" },
            ["FlexBasisAuto"] = new() { },
            ["Position"] = new() { ["YGEdge"] = "edge", ["float"] = "value" },
            ["PositionPercent"] = new() { ["YGEdge"] = "edge", ["float"] = "percent" },
            ["Margin"] = new() { ["YGEdge"] = "edge", ["float"] = "value" },
            ["MarginPercent"] = new() { ["YGEdge"] = "edge", ["float"] = "percent" },
            ["MarginAuto"] = new() { ["YGEdge"] = "edge" },
            ["Padding"] = new() { ["YGEdge"] = "edge", ["float"] = "value" },
            ["PaddingPercent"] = new() { ["YGEdge"] = "edge", ["float"] = "percent" },
            ["Border"] = new() { ["YGEdge"] = "edge", ["float"] = "value" },
            ["Gap"] = new() { ["YGGutter"] = "gutter", ["float"] = "gapLength" },
            ["AspectRatio"] = new() { ["float"] = "aspectRatio" },
            ["Width"] = new() { ["float"] = "width" },
            ["WidthPercent"] = new() { ["float"] = "widthPercent" },
            ["WidthAuto"] = new() { },
            ["Height"] = new() { ["float"] = "height" },
            ["HeightPercent"] = new() { ["float"] = "heightPercent" },
            ["HeightAuto"] = new() { },
            ["MinWidth"] = new() { ["float"] = "minWidth" },
            ["MinWidthPercent"] = new() { ["float"] = "minWidthPercent" },
            ["MinHeight"] = new() { ["float"] = "minHeight" },
            ["MinHeightPercent"] = new() { ["float"] = "minHeightPercent" },
            ["MaxWidth"] = new() { ["float"] = "maxWidth" },
            ["MaxWidthPercent"] = new() { ["float"] = "maxWidthPercent" },
            ["MaxHeight"] = new() { ["float"] = "maxHeight" },
            ["MaxHeightPercent"] = new() { ["float"] = "maxHeightPercent" },
        };

        public static string CLASS_NAME = "Style";
        public static string INTERFACE_NAME = "IFlexStyle";

        public static string YogaStyleSource() => @$"
        // <auto-generated/>
        #nullable enable

        using YogaSharp;

        namespace Flex
        {{
            public static partial class {CLASS_NAME} 
            {{
                {string.Join("\r\n", STYLES.Select((style) => FlexStyleSetter(style.Key, style.Value)))}
            }}
        }}

        namespace Flex.Internal
        {{
            {string.Join("\r\n", STYLES.Select((style) => FlexStyleStruct(style.Key, style.Value)))}
        }}
        ";

        public static string FlexStyleSetter(string name, Dictionary<string, string> attributes)
        {
            var hasAttributes = attributes.Count > 0;

            return $@"
            public static Internal.{CLASS_NAME}{name} Set{name}({INTERFACE_NAME}? style{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => $"{value.Key} {value.Value}"))}) => new(style{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => value.Value))});
            ";
        }

        public static string FlexStyleStruct(string name, Dictionary<string, string> attributes)
        {
            var hasAttributes = attributes.Count > 0;
            return $@"
            public unsafe record struct {CLASS_NAME}{name}({INTERFACE_NAME}? Style{(hasAttributes ? ", " : "")}{string.Join(", ", attributes.Select((value) => $"{value.Key} {value.Value.ToPascalCase()}"))}) : {INTERFACE_NAME}
            {{
                public void ApplyStyle(IFlexNode node)
                {{
                    node.GetHandle()->Set{name}({(hasAttributes ? string.Join(", ", attributes.Select((value) => value.Value.ToPascalCase())) : "")});
                    Style?.ApplyStyle(node);
                }} 
            }}
            ";
        }
    }
}
