name: push_release_nuget

on:
  push:
    branches:
      - feat/revamp
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@master
        with:
          submodules: "recursive"

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1

      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@v1

      - name: Publish VL Nuget
        uses: vvvv/PublishVLNuget@1.0.41
        with:
          csproj: src\VL.Yoga\Vl.Yoga.csproj
          nuspec: deployment\VL.Yoga.nuspec
          nuget-key: ${{ secrets.NUGET_KEY }}
