name: push_release_nuget

# on push on master
on:
  push:
    branches:
      - feat/nuget
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@master
      with:
        submodules: 'recursive'

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1

    -name: Apply Patch
      run: git apply --ignore-whitespace shared-build.patch

    - name: Build yogacore
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: yoga\yoga
        build-dir: lib\net8.0\Release\net8.0
      
    - name: Publish VL Nuget
      uses: vvvv/PublishVLNuget@1.0.41
      with:
        csproj: src\Vl.Yoga.csproj
        nuspec: deployment\VL.Yoga.nuspec
        nuget-key: ${{ secrets.NUGET_KEY }}
